import { 
  Tester, 
  CopyrightClaim, 
  FeedbackItem, 
  BroadcastMessage, 
  RoyaltyStreamEvent, 
  RoyaltyPoolSummary,
  SocietyFundMetrics,
  AppSubscriptionTally,
  UnregisteredEscrowClaim,
  SocietyDistributionRound,
  CreatorAccount,
  DirectMessage,
  MessageThread,
  StudioCreationWork
} from '../types';

export const INITIAL_TESTERS: Tester[] = [
  {
    id: 'tst_001',
    name: 'Cody Germain',
    email: 'codygermain032@gmail.com',
    github_handle: 'codygermain',
    role: 'App Creator',
    app_access_list: ['Tome Crafter', 'RLM Pro Studio', 'ForgeOS App Builder', 'RL Easy Flow'],
    current_subscription_status: 'Stripe Connect Active',
    stripe_account_id: 'acct_1NZcodyGermainReforge',
    joined_at: '2026-06-12T14:30:00Z',
    total_royalties_received: 4850.75,
    last_active: '2 minutes ago',
    license_keys: {
      'Tome Crafter': 'HUMAN-TOME-9921-X99',
      'RLM Pro Studio': 'HUMAN-RLM-8832-B71',
      'ForgeOS App Builder': 'HUMAN-FOS-1102-K44',
      'RL Easy Flow': 'HUMAN-RLE-7712-V19',
    },
    notes: 'Lead pioneer of H.U.M.A.N. Initiative and Ethical AI 4-App Suite.',
    email_welcomed: true,
  },
  {
    id: 'tst_002',
    name: 'Sarah Chen',
    email: 'sarah.chen@devforge.io',
    github_handle: 'sarahchen-oss',
    role: 'OSS Maintainer',
    app_access_list: ['ForgeOS App Builder', 'Tome Crafter'],
    current_subscription_status: 'Stripe Sandbox',
    stripe_account_id: 'acct_test_sarahChenOSS',
    joined_at: '2026-07-01T09:15:00Z',
    total_royalties_received: 1240.20,
    last_active: '18 minutes ago',
    license_keys: {
      'ForgeOS App Builder': 'HUMAN-FOS-4412-M12',
    },
    notes: 'Maintainer of zero-copyleft cleanroom AST compiler kernel.',
    email_welcomed: true,
  },
  {
    id: 'tst_003',
    name: 'Marcus Vance',
    email: 'marcus.v@audioartisan.net',
    github_handle: 'marcusvance-sound',
    role: 'Musician',
    app_access_list: ['RLM Pro Studio', 'RL Easy Flow'],
    current_subscription_status: 'Stripe Connect Active',
    stripe_account_id: 'acct_1NZmarcusAudioArt',
    joined_at: '2026-07-15T11:45:00Z',
    total_royalties_received: 3120.45,
    last_active: '1 hour ago',
    license_keys: {
      'RLM Pro Studio': 'HUMAN-RLM-3321-Z09',
    },
    notes: 'Acoustic stem library creator; earns 50% subscription distributions per audio stem synthesis.',
    email_welcomed: true,
  },
  {
    id: 'tst_004',
    name: 'Dr. Evelyn Morales',
    email: 'evelyn.design@tomecraft.org',
    github_handle: 'evelyn-author',
    role: 'Artisan Author',
    app_access_list: ['Tome Crafter', 'RL Easy Flow'],
    current_subscription_status: 'Active',
    stripe_account_id: 'acct_1NZevelynScholar',
    joined_at: '2026-08-02T16:20:00Z',
    total_royalties_received: 1890.10,
    last_active: '3 hours ago',
    license_keys: {
      'Tome Crafter': 'HUMAN-TOME-1188-A01',
    },
    notes: 'Published literary theorist and author in Tome Crafter writing engine.',
    email_welcomed: true,
  },
  {
    id: 'tst_005',
    name: 'David Rostami',
    email: 'david.r@quantum-syntax.com',
    github_handle: 'quantum-syntax',
    role: 'Beta Tester',
    app_access_list: ['ForgeOS App Builder', 'RL Easy Flow'],
    current_subscription_status: 'Stripe Sandbox',
    stripe_account_id: 'acct_test_davidRostami',
    joined_at: '2026-08-10T10:00:00Z',
    total_royalties_received: 140.00,
    last_active: 'Yesterday',
    license_keys: {
      'ForgeOS App Builder': 'HUMAN-FOS-7733-Q88',
    },
    notes: 'Evaluating cleanroom AST video & code pipeline guardrails.',
    email_welcomed: true,
  },
];

export const INITIAL_CLAIMS: CopyrightClaim[] = [
  {
    id: 'clm_101',
    title: 'ForgeOS Cleanroom AST Virtual Kernel & Guardrail SDK',
    creator_name: 'Cody Germain',
    creator_email: 'codygermain032@gmail.com',
    asset_type: 'Code Library',
    repository_or_source: 'https://github.com/codygermain/forgeos-kernel',
    evidence_description: 'Original AST runtime engine that prevents hallucinated code and enforces zero copyleft quarantine with automated NOTICE.txt generation in ForgeOS.',
    status: 'Verified',
    confidence_score: 99,
    attribution_share_bps: 450,
    micro_rate_usd: '$0.0045 / synthesis event + 50% Fund',
    bank_connected: true,
    stripe_account_id: 'acct_1NZcodyGermainReforge',
    payout_balance_usd: 342.80,
    total_payouts_claimed_usd: 4507.95,
    created_at: '2026-06-15T12:00:00Z',
    analysis_notes: 'Fully authenticated GitHub commit signature. Verified origin author of ForgeOS micro-royalty framework.',
  },
  {
    id: 'clm_102',
    title: 'Harmonic Stems Vol. 4 (RLM Pro Audio Loops)',
    creator_name: 'Marcus Vance',
    creator_email: 'marcus.v@audioartisan.net',
    asset_type: 'Music / Audio',
    repository_or_source: 'https://audiocraft-registry.org/works/hv4-stems',
    evidence_description: '128 master FLAC acoustic recordings sampled for generative melody synthesis in RLM Pro Studio.',
    status: 'Verified',
    confidence_score: 97,
    attribution_share_bps: 320,
    micro_rate_usd: '$0.0032 / stem invocation + 50% Fund',
    bank_connected: true,
    stripe_account_id: 'acct_1NZmarcusAudioArt',
    payout_balance_usd: 184.20,
    total_payouts_claimed_usd: 2936.25,
    created_at: '2026-07-20T08:30:00Z',
    analysis_notes: 'ISRC audio fingerprint matched to training weights. Direct Stripe Connect routing active.',
  },
  {
    id: 'clm_103',
    title: 'The Principles of Ethical AI Synthesis (Handbook)',
    creator_name: 'Dr. Evelyn Morales',
    creator_email: 'e.morales@artisans-guild.edu',
    asset_type: 'Book / Literature',
    repository_or_source: 'ISBN 978-1-987654-32-1 / Open Scholar',
    evidence_description: 'Peer-reviewed treatise on computational copyright attribution models utilized by Tome Crafter drafting engine.',
    status: 'Verified',
    confidence_score: 98,
    attribution_share_bps: 280,
    micro_rate_usd: '$0.0028 / citation query + 50% Fund',
    bank_connected: true,
    stripe_account_id: 'acct_1NZevelynScholar',
    payout_balance_usd: 512.60,
    total_payouts_claimed_usd: 1680.00,
    created_at: '2026-07-28T14:15:00Z',
    analysis_notes: 'Verified DOI and Open Academic Registry proof. Micro-royalties stream upon academic/RAG context lookup.',
  },
  {
    id: 'clm_104',
    title: 'Cinematic Dynamic Light Fields & Motion Textures',
    creator_name: 'Elena Rostova',
    creator_email: 'elena@kinoflow-studios.art',
    asset_type: 'Visual Art',
    repository_or_source: 'https://kinoflow.c2pa.registry/elena-lightfields-2026',
    evidence_description: 'Raw high-dynamic range 10-bit color motion keyframes used in RL Easy Flow procedural video synthesis.',
    status: 'Verified',
    confidence_score: 99,
    attribution_share_bps: 390,
    micro_rate_usd: '$0.0039 / video frame + 50% Fund',
    bank_connected: true,
    stripe_account_id: 'acct_1NZElenaRostovaVisualArt',
    payout_balance_usd: 424.48,
    total_payouts_claimed_usd: 3180.00,
    created_at: '2026-08-01T10:00:00Z',
    analysis_notes: 'C2PA JUMBF Manifest verified. Real-time frame provenance verified for RL Easy Flow.',
  },
];

export const INITIAL_FEEDBACK: FeedbackItem[] = [
  {
    id: 'fb_201',
    tester_id: 'tst_002',
    tester_name: 'Sarah Chen',
    tester_email: 'sarah.chen@devforge.io',
    app_name: 'ForgeOS App Builder',
    category: 'Bug',
    severity: 'High',
    subject: 'Stripe Sandbox webhook latency on AST tier upgrade',
    content: 'When testing the tier upgrade workflow in ForgeOS App Builder, the webhook takes ~4 seconds to acknowledge test tokens. Resetting sandbox solved it temporarily.',
    status: 'In Review',
    created_at: '2026-08-16T15:22:00Z',
    reply_history: [
      {
        sender: 'H.U.M.A.N. Initiative Admin',
        message: 'Investigating webhook retry backoff in sandbox container. Will patch in build v2.4.1.',
        timestamp: '2026-08-16T16:00:00Z',
      },
    ],
  },
  {
    id: 'fb_202',
    tester_id: 'tst_003',
    tester_name: 'Marcus Vance',
    tester_email: 'marcus.v@audioartisan.net',
    app_name: 'RLM Pro Studio',
    category: 'Feature Request',
    severity: 'Medium',
    subject: 'Add batch export for 50% micro-royalty invoice CSVs',
    content: 'Would love an option in the RLM Pro Studio console to export monthly Stripe Connect breakdown per music stem synthesized.',
    status: 'New',
    created_at: '2026-08-17T09:10:00Z',
  },
  {
    id: 'fb_203',
    tester_id: 'tst_005',
    tester_name: 'David Rostami',
    tester_email: 'david.r@quantum-syntax.com',
    app_name: 'RL Easy Flow',
    category: 'UX & Flow',
    severity: 'Low',
    subject: 'Frame-by-frame C2PA verification badge looks phenomenal',
    content: 'The zero-copyleft quarantine warning triggered accurately when rendering video segments. Super clean provenance trace in RL Easy Flow!',
    status: 'Resolved',
    created_at: '2026-08-17T18:40:00Z',
  },
  {
    id: 'fb_204',
    tester_id: 'tst_004',
    tester_name: 'Dr. Evelyn Morales',
    tester_email: 'evelyn.design@tomecraft.org',
    app_name: 'Tome Crafter',
    category: 'Feature Request',
    severity: 'Medium',
    subject: 'Direct ISBN registration integration in Tome Crafter',
    content: 'Can we add an automated ISBN lookup that auto-links existing author estates into the 50% Society Fund distribution table?',
    status: 'New',
    created_at: '2026-08-18T14:30:00Z',
  },
];

export const INITIAL_BROADCASTS: BroadcastMessage[] = [
  {
    id: 'bc_301',
    subject: 'H.U.M.A.N. Initiative 4-App Ecosystem: 50% Subscription Royalty Pool Live',
    body_text: 'Beta testers: The 50% subscription fund model is now live across Tome Crafter, RLM Pro Studio, ForgeOS App Builder, and RL Easy Flow. 50% of all SaaS subscription revenue is automatically escrowed and streamed to verified creators via Stripe Connect.',
    target_app: 'All Apps',
    recipients_count: 5,
    sent_at: '2026-08-15T12:00:00Z',
    status: 'Delivered',
    key_takeaways: ['4 Flagship Apps Connected', '50% Subscription Fund Model Active', 'C2PA Trust Badges Deployed'],
    sender_admin: 'Cody Germain (Lead Architect)',
  },
];

export const INITIAL_ROYALTY_EVENTS: RoyaltyStreamEvent[] = [
  {
    id: 'evt_001',
    timestamp: 'Just now',
    trigger_prompt: 'Synthesize cleanroom AST parser with zero-copyleft validation',
    app_source: 'ForgeOS App Builder',
    amount_cents: 4.8,
    recipient_name: 'Cody Germain',
    package_or_work: '@forgeos/kernel-ast',
    stripe_transfer_id: 'tr_test_99218A',
    audit_hash: '0x99e8a...331b',
  },
  {
    id: 'evt_002',
    timestamp: '1 min ago',
    trigger_prompt: 'Synthesize acoustic rhythm section with stereo separation',
    app_source: 'RLM Pro Studio',
    amount_cents: 3.2,
    recipient_name: 'Marcus Vance',
    package_or_work: 'Harmonic Stems Vol. 4',
    stripe_transfer_id: 'tr_test_88192K',
    audit_hash: '0x71fa0...c902',
  },
  {
    id: 'evt_003',
    timestamp: '4 mins ago',
    trigger_prompt: 'Generate literature chapter outline citing narrative ethics handbook',
    app_source: 'Tome Crafter',
    amount_cents: 2.8,
    recipient_name: 'Dr. Evelyn Morales',
    package_or_work: 'The Principles of Ethical AI Synthesis',
    stripe_transfer_id: 'tr_test_11209B',
    audit_hash: '0x43bc1...e881',
  },
  {
    id: 'evt_004',
    timestamp: '7 mins ago',
    trigger_prompt: 'Render 60fps cinematic procedural lighting pass',
    app_source: 'RL Easy Flow',
    amount_cents: 3.9,
    recipient_name: 'Elena Rostova',
    package_or_work: 'Cinematic Dynamic Light Fields',
    stripe_transfer_id: 'tr_test_55412C',
    audit_hash: '0x12fe9...a004',
  },
];

export const INITIAL_SUMMARY: RoyaltyPoolSummary = {
  total_streamed_usd: 128450.00,
  total_active_creators: 1420,
  total_synthesis_events: 384910,
  copyleft_quarantine_violations: 0,
  active_badge_apps: 4,
  monthly_pool_growth_pct: 34.8,
  society_fund_balance_usd: 76408.00,
  unallocated_holding_escrow_usd: 14280.00,
  total_active_subscribers: 4080,
};

export const INITIAL_APP_SUBSCRIPTIONS: AppSubscriptionTally[] = [
  {
    app_id: 'tomecrafter-ai-book-studio',
    app_name: 'Tome Crafter',
    app_url: 'https://tomecrafter-ai-book-studio.ai.studio',
    badge_status: 'Active',
    subscribers_count: 1420,
    plan_price_monthly: 29.00,
    gross_monthly_mrr: 41180.00,
    society_fund_40pct_contribution: 16472.00,
    c2pa_audit_id: 'FT-ETHIC-TOMECRAFTER-2026',
    icon_category: 'book',
  },
  {
    app_id: 'remix-lyria-studio-5954',
    app_name: 'RLM Pro Studio',
    app_url: 'https://remix-lyria-studio-5954.ai.studio',
    badge_status: 'Active',
    subscribers_count: 890,
    plan_price_monthly: 49.00,
    gross_monthly_mrr: 43610.00,
    society_fund_40pct_contribution: 17444.00,
    c2pa_audit_id: 'FT-ETHIC-RLM-AUDIO-2026',
    icon_category: 'audio',
  },
  {
    app_id: 'forgeos-app-builder-tester',
    app_name: 'ForgeOS App Builder',
    app_url: 'https://forgeos-app-builder-tester-console-416188261320.us-east1.run.app',
    badge_status: 'Active',
    subscribers_count: 620,
    plan_price_monthly: 99.00,
    gross_monthly_mrr: 61380.00,
    society_fund_40pct_contribution: 24552.00,
    c2pa_audit_id: 'FT-ETHIC-FORGEOS-APPBUILDER-2026',
    icon_category: 'code',
  },
  {
    app_id: 'rl-easy-flow',
    app_name: 'RL Easy Flow',
    app_url: 'https://rl-easy-flow.ai.studio',
    badge_status: 'Active',
    subscribers_count: 1150,
    plan_price_monthly: 39.00,
    gross_monthly_mrr: 44850.00,
    society_fund_40pct_contribution: 17940.00,
    c2pa_audit_id: 'FT-ETHIC-RL-EASY-FLOW-2026',
    icon_category: 'video',
  },
];

export const INITIAL_UNREGISTERED_ESCROW: UnregisteredEscrowClaim[] = [
  {
    id: 'escrow_unreg_01',
    work_title: 'Algorithmic Graph Traversal AST Kernels (C++ / WASM)',
    detected_author_or_source: 'Unknown OSS Maintainer (GitHub commit signature @graph-core-v3)',
    asset_type: 'Code Library',
    holding_escrow_balance_usd: 5420.00,
    subscribers_referencing_count: 620,
    first_accrued_at: '2026-07-02T10:00:00Z',
    c2pa_manifest_hash: '0x88f1a...wasm44',
    status: 'Awaiting Creator Registration',
  },
  {
    id: 'escrow_unreg_02',
    work_title: 'Atmospheric Binaural Modular Soundscapes',
    detected_author_or_source: 'Master Rights Holder (Audio fingerprint #AC-9912 in RLM Pro Studio)',
    asset_type: 'Music / Audio',
    holding_escrow_balance_usd: 4680.00,
    subscribers_referencing_count: 890,
    first_accrued_at: '2026-07-10T14:30:00Z',
    c2pa_manifest_hash: '0x4f1b8...audio88',
    status: 'Awaiting Creator Registration',
  },
  {
    id: 'escrow_unreg_03',
    work_title: 'Lexicon of Semantic Narratology & Sci-Fi Tropes',
    detected_author_or_source: 'Author Guild Registered Estate (ISBN reference 978-0-12948-11 in Tome Crafter)',
    asset_type: 'Book / Literature',
    holding_escrow_balance_usd: 4180.00,
    subscribers_referencing_count: 1420,
    first_accrued_at: '2026-07-18T09:15:00Z',
    c2pa_manifest_hash: '0x33b4c...tome11',
    status: 'Awaiting Creator Registration',
  },
];

export const INITIAL_DISTRIBUTION_ROUNDS: SocietyDistributionRound[] = [
  {
    round_id: 'dist_round_2026_07',
    timestamp: '2026-07-31 23:59 UTC',
    total_distributed_usd: 62140.00,
    subscribers_at_execution: 3410,
    creators_paid_count: 142,
    average_payout_per_creator: 437.60,
    status: 'Completed',
    stripe_batch_id: 'batch_tr_stripe_connect_2026_07_final',
    c2pa_audit_seal: '0x8a92...auditJuly26',
  },
  {
    round_id: 'dist_round_2026_08_mid',
    timestamp: '2026-08-15 23:59 UTC',
    total_distributed_usd: 68950.00,
    subscribers_at_execution: 3820,
    creators_paid_count: 156,
    average_payout_per_creator: 441.98,
    status: 'Completed',
    stripe_batch_id: 'batch_tr_stripe_connect_2026_08_mid',
    c2pa_audit_seal: '0x4f1b...auditAug15',
  },
  {
    round_id: 'dist_round_2026_08_scheduled',
    timestamp: '2026-08-31 23:59 UTC (Scheduled)',
    total_distributed_usd: 76408.00,
    subscribers_at_execution: 4080,
    creators_paid_count: 180,
    average_payout_per_creator: 424.48,
    status: 'Scheduled',
    stripe_batch_id: 'batch_tr_stripe_connect_pending_run',
    c2pa_audit_seal: '0x93de...auditPending',
  },
];

export const INITIAL_SOCIETY_FUND_METRICS: SocietyFundMetrics = {
  total_subscription_revenue_usd: 191020.00,
  society_fund_share_pct: 50,
  total_society_fund_usd: 95510.00,
  unallocated_holding_escrow_usd: 14280.00,
  allocated_registered_pool_usd: 81230.00,
  total_active_subscribers: 4080,
  average_monthly_sub_price: 46.82,
  per_subscriber_royalty_yield: 23.41,
  estimated_payout_per_registered_creator: 451.28,
  total_registered_creators: 180,
  total_unregistered_claims: 3,
  total_badge_integrated_apps: 4,
  last_distribution_timestamp: '2026-08-15T23:59:00Z',
};

export const INITIAL_CREATOR_ACCOUNTS: CreatorAccount[] = [
  {
    id: 'creator_001',
    name: 'Dr. Arthur Pendelton',
    email: 'arthur.pendelton@literary-estate.org',
    category: 'Book / Literature',
    stripe_account_id: 'acct_1NZArthurPendeltonTome',
    stripe_status: 'Connected',
    registered_works_count: 4,
    total_earned_usd: 4850.75,
    available_balance_usd: 424.48,
    c2pa_did: 'did:c2pa:arthur.pendelton.literary.2026',
    joined_at: '2026-06-12T14:30:00Z',
    bio: 'Author and literary theorist specializing in structural narrative theory and Tome Crafter narrative engines.',
    is_verified_human: true,
  },
  {
    id: 'creator_002',
    name: 'Marcus Sterling',
    email: 'marcus@soundcraft-audio.io',
    category: 'Music / Audio',
    stripe_account_id: 'acct_1NZm99StripeAudioDirect',
    stripe_status: 'Connected',
    registered_works_count: 8,
    total_earned_usd: 3940.20,
    available_balance_usd: 424.48,
    c2pa_did: 'did:c2pa:marcus.sterling.audio.2026',
    joined_at: '2026-06-18T09:15:00Z',
    bio: 'Producer and sound designer behind RLM Pro Studio harmonic acoustic stems and binaural datasets.',
    is_verified_human: true,
  },
  {
    id: 'creator_003',
    name: 'Evelyn Vance',
    email: 'evelyn@forgeos-foundation.dev',
    category: 'Code Library',
    stripe_account_id: 'acct_1NZEvelynVanceReforgeAST',
    stripe_status: 'Connected',
    registered_works_count: 6,
    total_earned_usd: 7820.50,
    available_balance_usd: 512.60,
    c2pa_did: 'did:c2pa:evelyn.vance.ast.cleanroom.2026',
    joined_at: '2026-05-20T11:00:00Z',
    bio: 'Open-source maintainer and AST compiler engineer creating zero-copyleft cleanroom abstractions for ForgeOS App Builder.',
    is_verified_human: true,
  },
  {
    id: 'creator_004',
    name: 'Elena Rostova',
    email: 'elena@kinoflow-studios.art',
    category: 'Visual Art',
    stripe_account_id: 'acct_1NZElenaRostovaVisualArt',
    stripe_status: 'Connected',
    registered_works_count: 5,
    total_earned_usd: 3180.00,
    available_balance_usd: 424.48,
    c2pa_did: 'did:c2pa:elena.rostova.cinematic.2026',
    joined_at: '2026-07-01T16:20:00Z',
    bio: 'Cinematographer and colorist providing RL Easy Flow procedural motion keyframes and textures.',
    is_verified_human: true,
  },
];

export const INITIAL_MESSAGE_THREADS: MessageThread[] = [
  {
    id: 'thread_001',
    creator_email: 'arthur.pendelton@literary-estate.org',
    creator_name: 'Dr. Arthur Pendelton',
    work_title: 'Tome Crafter Complete Drafting Engine',
    subject: '50% Subscription Payout Confirmation & August Distribution',
    status: 'Resolved',
    last_message_at: '2026-08-19 18:40 UTC',
    last_message_preview: 'Your 50% subscription allocation of $530.60 has been queued for immediate Stripe Connect transfer.',
    messages_count: 3,
    unread_count: 0,
    category: 'Royalty Payout',
  },
  {
    id: 'thread_002',
    creator_email: 'marcus@soundcraft-audio.io',
    creator_name: 'Marcus Sterling',
    work_title: 'Harmonic Stems Vol. 4 (RLM Pro Audio)',
    subject: 'C2PA JUMBF Manifest Verification & Stem Licensing',
    status: 'Open',
    last_message_at: '2026-08-20 08:30 UTC',
    last_message_preview: 'Can you verify that stem #44 is signed with the Fairly Trained v2 audio watermark in RLM Pro Studio?',
    messages_count: 2,
    unread_count: 1,
    category: 'C2PA Claim',
  },
  {
    id: 'thread_003',
    creator_email: 'evelyn@forgeos-foundation.dev',
    creator_name: 'Evelyn Vance',
    work_title: 'ForgeOS AST Cleanroom Kernel',
    subject: 'Escrow Release for WASM Graph Traversal Algorithms',
    status: 'Action Needed',
    last_message_at: '2026-08-19 14:15 UTC',
    last_message_preview: 'Awaiting formal author verification to release the $5,420 holding escrow balance.',
    messages_count: 4,
    unread_count: 2,
    category: 'Activation',
  },
  {
    id: 'thread_004',
    creator_email: 'elena@kinoflow-studios.art',
    creator_name: 'Elena Rostova',
    work_title: 'RL Easy Flow Procedural Kinetic Textures',
    subject: 'Subscriber Scaling Milestone: 1,150 Active Subscribers',
    status: 'Open',
    last_message_at: '2026-08-18 11:20 UTC',
    last_message_preview: 'Congratulations! RL Easy Flow just crossed 1,150 active subscribers, boosting the 50% fund by $22,425/mo.',
    messages_count: 2,
    unread_count: 0,
    category: 'Royalty Payout',
  },
];

export const INITIAL_DIRECT_MESSAGES: DirectMessage[] = [
  {
    id: 'msg_001',
    thread_id: 'thread_001',
    sender_type: 'admin',
    sender_name: 'H.U.M.A.N. Initiative Steward',
    sender_email: 'stewards@humanethical.ai',
    recipient_name: 'Dr. Arthur Pendelton',
    recipient_email: 'arthur.pendelton@literary-estate.org',
    subject: '50% Subscription Payout Confirmation & August Distribution',
    message_text: 'Dear Dr. Pendelton, we are pleased to confirm that Tome Crafter has surpassed 1,420 paying subscribers. Exactly 50% of all monthly subscriptions have been collected into the Society Fund escrow.',
    timestamp: '2026-08-19 14:00 UTC',
    is_read: true,
    work_reference: 'Tome Crafter Complete Drafting Engine',
    c2pa_attachment_hash: '0x633270612e6175646974...cody',
    category: 'Royalty Payout',
  },
  {
    id: 'msg_002',
    thread_id: 'thread_001',
    sender_type: 'creator',
    sender_name: 'Dr. Arthur Pendelton',
    sender_email: 'arthur.pendelton@literary-estate.org',
    recipient_name: 'H.U.M.A.N. Initiative Steward',
    recipient_email: 'stewards@humanethical.ai',
    subject: 'Re: 50% Subscription Payout Confirmation & August Distribution',
    message_text: 'Thank you! The automated Stripe Connect payout came through seamlessly into our estate account. The C2PA audit log transparency is exemplary.',
    timestamp: '2026-08-19 16:30 UTC',
    is_read: true,
    work_reference: 'Tome Crafter Complete Drafting Engine',
    category: 'Royalty Payout',
  },
  {
    id: 'msg_003',
    thread_id: 'thread_001',
    sender_type: 'admin',
    sender_name: 'H.U.M.A.N. Initiative Steward',
    sender_email: 'stewards@humanethical.ai',
    recipient_name: 'Dr. Arthur Pendelton',
    recipient_email: 'arthur.pendelton@literary-estate.org',
    subject: 'Re: 50% Subscription Payout Confirmation & August Distribution',
    message_text: 'Your 50% subscription allocation of $530.60 has been queued for immediate Stripe Connect transfer with C2PA Merkle seal 0x8a92...auditJuly26.',
    timestamp: '2026-08-19 18:40 UTC',
    is_read: true,
    work_reference: 'Tome Crafter Complete Drafting Engine',
    c2pa_attachment_hash: '0x8a92...auditJuly26',
    category: 'Royalty Payout',
  },
  {
    id: 'msg_004',
    thread_id: 'thread_002',
    sender_type: 'creator',
    sender_name: 'Marcus Sterling',
    sender_email: 'marcus@soundcraft-audio.io',
    recipient_name: 'H.U.M.A.N. Initiative Steward',
    recipient_email: 'stewards@humanethical.ai',
    subject: 'C2PA JUMBF Manifest Verification & Stem Licensing',
    message_text: 'Can you verify that stem #44 is signed with the Fairly Trained v2 audio watermark and that the 50% subscriber split includes remix stems from RLM Pro Studio?',
    timestamp: '2026-08-20 08:30 UTC',
    is_read: false,
    work_reference: 'Harmonic Stems Vol. 4 (RLM Pro Audio)',
    category: 'C2PA Claim',
  },
  {
    id: 'msg_005',
    thread_id: 'thread_003',
    sender_type: 'admin',
    sender_name: 'H.U.M.A.N. Initiative Steward',
    sender_email: 'stewards@humanethical.ai',
    recipient_name: 'Evelyn Vance',
    recipient_email: 'evelyn@forgeos-foundation.dev',
    subject: 'Escrow Release for WASM Graph Traversal Algorithms',
    message_text: 'A total of $5,420.00 is currently sitting in holding escrow for the WASM Graph Traversal Algorithms. Please complete the one-click personhood signature to release it directly to your Stripe Connect account.',
    timestamp: '2026-08-19 14:15 UTC',
    is_read: false,
    work_reference: 'ForgeOS AST Cleanroom Kernel',
    c2pa_attachment_hash: '0x88f1a...wasm44',
    category: 'Activation',
  },
];

export const INITIAL_STUDIO_CREATIONS: StudioCreationWork[] = [
  {
    id: 'work_tc_001',
    creator_id: 'cr_new_001',
    creator_name: 'Elena Rostova',
    creator_email: 'elena.rostova@emergentauthors.org',
    title: 'The Cartographer of Obsidian Tides (Chapter 1 & World Codex)',
    category: 'Book / Literature',
    summary: 'An original speculative fiction manuscript and modular worldbuilding codex crafted for procedural generation and literary style grounding in Tome Crafter.',
    content_payload: `# The Cartographer of Obsidian Tides\n\n## Chapter 1: The Glass Horizon\n\nThe salt flats did not reflect the morning sun; they devoured it. Captain Lyra Vane stood upon the obsidian outcrop, running her weathered fingertips over the brass sextant. In the old hemisphere before the Great Shift, tides obeyed the moon. Now, the ocean hummed with a magnetic pulse that mirrored the rhythmic breathing of deep-earth geothermal engines...\n\n### Narrative Resonance Codex\n- Atmosphere: Atmospheric dieselpunk realism with lyrical nautical cadences.\n- Sensory Anchor: Smells of petrichor, ozone, and crystallized sea brine.`,
    metadata: {
      wordCount: 1420,
      genreTags: ['Speculative Fiction', 'Worldbuilding Codex', 'Literary Prose'],
      originalityIndex: 99.2,
      humanEffortHours: 34.5,
    },
    human_touch_score: 99.2,
    cleanroom_zero_copyleft_verified: true,
    c2pa_manifest_hash: '0x9b44a7f0128e404b9982dc8e81992ad317765ec1',
    c2pa_jumbf_manifest_urn: 'urn:c2pa:human:creation:work_tc_001:2026',
    c2pa_signature_timestamp: '2026-08-18T14:20:00Z',
    registration_status: 'Active in Society Fund',
    assigned_apps: ['Tome Crafter', 'RL Easy Flow'],
    royalty_yield_share_bps: 280, // 2.8%
    earned_royalties_usd: 348.60,
    synthesis_references_count: 842,
    stripe_payout_ready: true,
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-08-18T14:20:00Z',
  },
  {
    id: 'work_rlm_002',
    creator_id: 'cr_new_002',
    creator_name: 'Kaelen Vance & The Resonance Collective',
    creator_email: 'kaelen.vance@modularsound.io',
    title: 'Warm Analog Tape & Polyphonic Dreamscape (16-Stem Audio Pack)',
    category: 'Music / Audio',
    summary: 'A pristine zero-sample analog synthesizer stem pack recorded on vintage tape machines, structured for AI music synthesis in RLM Pro Studio.',
    content_payload: `[STEM_MANIFEST_V2]\nBPM: 118\nKEY: D_MINOR\nTRACKS: [Sub_Bass_Moog_D, Poly_Chords_Juno106, Vinyl_Noise_Floor, Reverb_Bell_Arp, Acoustic_Kick_Felt]\nDYNAMIC_RANGE: -14 LUFS\nTIMBRE_SIGNATURE: Harmonic Saturation with Warm Neutral EQ`,
    metadata: {
      audioBpm: 118,
      audioKey: 'D Minor',
      melodicPattern: ['D3', 'F3', 'A3', 'C4', 'G3', 'Bb3', 'D4', 'F4'],
      genreTags: ['Neo-Ambient', 'Tape Synthesis', 'Polyphonic Stems'],
      originalityIndex: 98.6,
      humanEffortHours: 42.0,
    },
    human_touch_score: 98.6,
    cleanroom_zero_copyleft_verified: true,
    c2pa_manifest_hash: '0x17c9339e08819ab238f9024bc66120ef7781a542',
    c2pa_jumbf_manifest_urn: 'urn:c2pa:human:creation:work_rlm_002:2026',
    c2pa_signature_timestamp: '2026-08-17T09:12:00Z',
    registration_status: 'Active in Society Fund',
    assigned_apps: ['RLM Pro Studio', 'RL Easy Flow'],
    royalty_yield_share_bps: 350, // 3.5%
    earned_royalties_usd: 512.40,
    synthesis_references_count: 1290,
    stripe_payout_ready: true,
    created_at: '2026-08-14T08:30:00Z',
    updated_at: '2026-08-17T09:12:00Z',
  },
  {
    id: 'work_fos_003',
    creator_id: 'cr_new_003',
    creator_name: 'Devin Thorne',
    creator_email: 'devin.thorne@cleanroom-kernels.dev',
    title: 'Reactive Topological Canvas DAG & State Synchronization Engine',
    category: 'Code Library',
    summary: 'A cleanroom MIT-licensed topological sorting Directed Acyclic Graph engine written from first principles for ForgeOS App Builder.',
    content_payload: `/**\n * @license MIT - H.U.M.A.N. Initiative Verified Cleanroom Creation\n * @author Devin Thorne <devin.thorne@cleanroom-kernels.dev>\n * Zero-Dependency Topological Graph Dependency Resolver\n */\nexport class TopologicalExecutionGraph<TNodeId extends string, TData> {\n  private nodes = new Map<TNodeId, { data: TData; dependencies: Set<TNodeId> }>();\n  \n  public registerNode(id: TNodeId, data: TData, deps: TNodeId[] = []): void {\n    this.nodes.set(id, { data, dependencies: new Set(deps) });\n  }\n\n  public computeTopologicalExecutionOrder(): TNodeId[] {\n    const visited = new Set<TNodeId>();\n    const visiting = new Set<TNodeId>();\n    const order: TNodeId[] = [];\n\n    const visit = (id: TNodeId) => {\n      if (visiting.has(id)) throw new Error(\`Circular dependency detected at node \${id}\`);\n      if (!visited.has(id)) {\n        visiting.add(id);\n        const node = this.nodes.get(id);\n        if (node) {\n          for (const dep of node.dependencies) visit(dep);\n        }\n        visiting.delete(id);\n        visited.add(id);\n        order.push(id);\n      }\n    };\n\n    for (const key of this.nodes.keys()) {\n      if (!visited.has(key)) visit(key);\n    }\n    return order;\n  }\n}`,
    metadata: {
      codeLanguage: 'TypeScript',
      codeAstNodes: 184,
      genreTags: ['Data Structures', 'Cleanroom Algorithm', 'ForgeOS Extension'],
      originalityIndex: 99.8,
      humanEffortHours: 19.5,
    },
    human_touch_score: 99.8,
    cleanroom_zero_copyleft_verified: true,
    c2pa_manifest_hash: '0x43ef8110bce9042a981cba9087e14f8812cde441',
    c2pa_jumbf_manifest_urn: 'urn:c2pa:human:creation:work_fos_003:2026',
    c2pa_signature_timestamp: '2026-08-16T17:45:00Z',
    registration_status: 'Active in Society Fund',
    assigned_apps: ['ForgeOS App Builder', 'RL Easy Flow'],
    royalty_yield_share_bps: 220, // 2.2%
    earned_royalties_usd: 278.90,
    synthesis_references_count: 674,
    stripe_payout_ready: true,
    created_at: '2026-08-13T12:00:00Z',
    updated_at: '2026-08-16T17:45:00Z',
  },
  {
    id: 'work_art_004',
    creator_id: 'cr_new_004',
    creator_name: 'Aria Thorne-Lin',
    creator_email: 'aria.illustrations@humanartisan.co',
    title: 'Cyber-Agrarian Vector Iconography & Geometric Motif Set',
    category: 'Visual Art',
    summary: 'A cohesive vector art system depicting ecological architecture and human-AI balance for ethical app UI themes.',
    content_payload: `<svg viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">\n  <circle cx="100" cy="100" r="88" stroke="#5A5A40" stroke-width="4" stroke-dasharray="8 6" />\n  <path d="M100 24V176M24 100H176" stroke="#DCD5CA" stroke-width="2" />\n  <polygon points="100,45 155,140 45,140" stroke="#D67D5C" stroke-width="3" fill="#D67D5C" fill-opacity="0.15" />\n  <circle cx="100" cy="100" r="16" fill="#3D6E50" />\n  <path d="M70 125 C 85 90, 115 90, 130 125" stroke="#2D2926" stroke-width="2.5" stroke-linecap="round" />\n</svg>`,
    metadata: {
      visualPalette: ['#5A5A40', '#D67D5C', '#3D6E50', '#FAF8F5', '#2D2926'],
      svgCode: '<svg>...</svg>',
      genreTags: ['Vector Art', 'Bio-Cybernetic Icons', 'Creative Commons Clean'],
      originalityIndex: 97.4,
      humanEffortHours: 28.0,
    },
    human_touch_score: 97.4,
    cleanroom_zero_copyleft_verified: true,
    c2pa_manifest_hash: '0x77ab1289cf001239ab782910fedcba4455667788',
    c2pa_jumbf_manifest_urn: 'urn:c2pa:human:creation:work_art_004:2026',
    c2pa_signature_timestamp: '2026-08-18T19:00:00Z',
    registration_status: 'Active in Society Fund',
    assigned_apps: ['Tome Crafter', 'ForgeOS App Builder', 'RL Easy Flow'],
    royalty_yield_share_bps: 190, // 1.9%
    earned_royalties_usd: 194.50,
    synthesis_references_count: 480,
    stripe_payout_ready: true,
    created_at: '2026-08-16T15:30:00Z',
    updated_at: '2026-08-18T19:00:00Z',
  }
];
