import { 
  Tester, 
  CopyrightClaim, 
  FeedbackItem, 
  BroadcastMessage, 
  RoyaltyStreamEvent, 
  RoyaltyPoolSummary 
} from '../types';

export const INITIAL_TESTERS: Tester[] = [
  {
    id: 'tst_001',
    name: 'Cody Germain',
    email: 'codygermain032@gmail.com',
    github_handle: 'codygermain',
    role: 'App Creator',
    app_access_list: ['ShareShop Pro', 'Lyria Studio', 'CodeSynthesizer', 'ReForgeOS Engine'],
    current_subscription_status: 'Stripe Connect Active',
    stripe_account_id: 'acct_1NZcodyGermainReforge',
    joined_at: '2026-06-12T14:30:00Z',
    total_royalties_received: 4850.75,
    last_active: '2 minutes ago',
    license_keys: {
      'ShareShop Pro': 'HUMAN-SSP-9921-X99',
      'Lyria Studio': 'HUMAN-LYR-8832-B71',
      'ReForgeOS Engine': 'HUMAN-RFE-1102-K44',
    },
    notes: 'Lead pioneer of H.U.M.A.N. and ReForgeOS Ethical AI Network.',
    email_welcomed: true,
  },
  {
    id: 'tst_002',
    name: 'Sarah Chen',
    email: 'sarah.chen@devforge.io',
    github_handle: 'sarahchen-oss',
    role: 'OSS Maintainer',
    app_access_list: ['ShareShop Pro', 'CodeSynthesizer'],
    current_subscription_status: 'Stripe Sandbox',
    stripe_account_id: 'acct_test_sarahChenOSS',
    joined_at: '2026-07-01T09:15:00Z',
    total_royalties_received: 1240.20,
    last_active: '18 minutes ago',
    license_keys: {
      'ShareShop Pro': 'HUMAN-SSP-4412-M12',
    },
    notes: 'Maintainer of @fast-router and web component ecosystem.',
    email_welcomed: true,
  },
  {
    id: 'tst_003',
    name: 'Marcus Vance',
    email: 'marcus.v@audioartisan.net',
    github_handle: 'marcusvance-sound',
    role: 'Musician',
    app_access_list: ['Lyria Studio', 'ArtisanPay API'],
    current_subscription_status: 'Stripe Connect Active',
    stripe_account_id: 'acct_1NZmarcusAudioArt',
    joined_at: '2026-07-15T11:45:00Z',
    total_royalties_received: 3120.45,
    last_active: '1 hour ago',
    license_keys: {
      'Lyria Studio': 'HUMAN-LYR-3321-Z09',
    },
    notes: 'Acoustic sample library creator; earns micro-patronage per synthesized audio stem.',
    email_welcomed: true,
  },
  {
    id: 'tst_004',
    name: 'Amina Al-Mansoor',
    email: 'amina.design@lyriacraft.org',
    github_handle: 'amina-vector',
    role: 'Artisan Author',
    app_access_list: ['ShareShop Pro', 'Lyria Studio'],
    current_subscription_status: 'Trial',
    stripe_account_id: 'acct_test_aminaCraft',
    joined_at: '2026-08-02T16:20:00Z',
    total_royalties_received: 890.10,
    last_active: '3 hours ago',
    license_keys: {
      'ShareShop Pro': 'HUMAN-SSP-1188-A01',
    },
    notes: 'Vector glyph designer and typography author.',
    email_welcomed: false,
  },
  {
    id: 'tst_005',
    name: 'David Rostami',
    email: 'david.r@quantum-syntax.com',
    github_handle: 'quantum-syntax',
    role: 'Beta Tester',
    app_access_list: ['CodeSynthesizer', 'ReForgeOS Engine'],
    current_subscription_status: 'Stripe Sandbox',
    stripe_account_id: 'acct_test_davidRostami',
    joined_at: '2026-08-10T10:00:00Z',
    total_royalties_received: 140.00,
    last_active: 'Yesterday',
    license_keys: {
      'CodeSynthesizer': 'HUMAN-CSY-7733-Q88',
    },
    notes: 'Evaluating 5-stage testing guardrail compiler.',
    email_welcomed: true,
  },
];

export const INITIAL_CLAIMS: CopyrightClaim[] = [
  {
    id: 'clm_101',
    title: 'ReForgeOS Virtual Kernel & Guardrail SDK',
    creator_name: 'Cody Germain',
    creator_email: 'codygermain032@gmail.com',
    asset_type: 'Code Library',
    repository_or_source: 'https://github.com/codygermain/reforge-os-kernel',
    evidence_description: 'Original runtime engine that prevents hallucinated code and enforces zero copyleft quarantine with automated NOTICE.txt generation.',
    status: 'Verified',
    confidence_score: 99,
    attribution_share_bps: 450,
    micro_rate_usd: '$0.0045 / synthesis event',
    bank_connected: true,
    stripe_account_id: 'acct_1NZcodyGermainReforge',
    payout_balance_usd: 342.80,
    total_payouts_claimed_usd: 4507.95,
    created_at: '2026-06-15T12:00:00Z',
    analysis_notes: 'Fully authenticated GitHub commit signature. Verified origin author of ReForgeOS micro-royalty framework.',
  },
  {
    id: 'clm_102',
    title: 'Harmonic Stems Vol. 4 (Acoustic Guitar Loops)',
    creator_name: 'Marcus Vance',
    creator_email: 'marcus.v@audioartisan.net',
    asset_type: 'Music / Audio',
    repository_or_source: 'https://audiocraft-registry.org/works/hv4-stems',
    evidence_description: '128 master FLAC acoustic recordings sampled for generative melody synthesis in Lyria Studio.',
    status: 'Verified',
    confidence_score: 97,
    attribution_share_bps: 320,
    micro_rate_usd: '$0.0032 / stem invocation',
    bank_connected: true,
    stripe_account_id: 'acct_1NZmarcusAudioArt',
    payout_balance_usd: 184.20,
    total_payouts_claimed_usd: 2936.25,
    created_at: '2026-07-20T08:30:00Z',
    analysis_notes: 'ISRC audio fingerprint matched to training weights. Direct Stripe Connect routing active.',
  },
  {
    id: 'clm_103',
    title: 'The Principles of Ethical AI Synthesis (Handbook)',
    creator_name: 'Dr. Evelyn Morales',
    creator_email: 'e.morales@artisans-guild.edu',
    asset_type: 'Book / Literature',
    repository_or_source: 'ISBN 978-1-987654-32-1 / Open Scholar',
    evidence_description: 'Peer-reviewed treatise on computational copyright attribution models and fair micro-compensation.',
    status: 'Verified',
    confidence_score: 98,
    attribution_share_bps: 280,
    micro_rate_usd: '$0.0028 / citation query',
    bank_connected: true,
    stripe_account_id: 'acct_1NZevelynScholar',
    payout_balance_usd: 512.60,
    total_payouts_claimed_usd: 1680.00,
    created_at: '2026-07-28T14:15:00Z',
    analysis_notes: 'Verified DOI and Open Academic Registry proof. Micro-royalties stream upon academic/RAG context lookup.',
  },
];

export const INITIAL_FEEDBACK: FeedbackItem[] = [
  {
    id: 'fb_201',
    tester_id: 'tst_002',
    tester_name: 'Sarah Chen',
    tester_email: 'sarah.chen@devforge.io',
    app_name: 'ShareShop Pro',
    category: 'Bug',
    severity: 'High',
    subject: 'Stripe Sandbox webhook delay on tier upgrade',
    content: 'When testing the tier upgrade workflow in ShareShop Pro, the webhook takes ~4 seconds to acknowledge test tokens. Resetting sandbox solved it temporarily.',
    status: 'In Review',
    created_at: '2026-08-16T15:22:00Z',
    reply_history: [
      {
        sender: 'ReForgeOS Admin',
        message: 'Investigating webhook retry backoff in sandbox container. Will patch in build v2.4.1.',
        timestamp: '2026-08-16T16:00:00Z',
      },
    ],
  },
  {
    id: 'fb_202',
    tester_id: 'tst_003',
    tester_name: 'Marcus Vance',
    tester_email: 'marcus.v@audioartisan.net',
    app_name: 'Lyria Studio',
    category: 'Feature Request',
    severity: 'Medium',
    subject: 'Add batch export for micro-royalty invoice CSVs',
    content: 'Would love an option in the Lyria Studio console to export monthly Stripe Connect breakdown per music stem synthesized.',
    status: 'New',
    created_at: '2026-08-17T09:10:00Z',
  },
  {
    id: 'fb_203',
    tester_id: 'tst_005',
    tester_name: 'David Rostami',
    tester_email: 'david.r@quantum-syntax.com',
    app_name: 'CodeSynthesizer',
    category: 'UX & Flow',
    severity: 'Low',
    subject: '5-Stage testing guardrail preview looks phenomenal',
    content: 'The zero-copyleft quarantine warning triggered accurately when importing an unverified GPL snippet. Super clean error trace!',
    status: 'Resolved',
    created_at: '2026-08-17T18:40:00Z',
  },
];

export const INITIAL_BROADCASTS: BroadcastMessage[] = [
  {
    id: 'bc_301',
    subject: 'Welcome to H.U.M.A.N. Beta Wave 2: Micro-Royalty Stream Live',
    body_text: 'Beta testers: We have initiated the live Stripe Sandbox micro-patronage pool. All synthesis events in ShareShop Pro and Lyria Studio now stream test royalties in real time to connected creator accounts.',
    target_app: 'All Apps',
    recipients_count: 5,
    sent_at: '2026-08-15T12:00:00Z',
    status: 'Delivered',
    key_takeaways: ['Stripe Sandbox active', '5-Stage guardrails live', 'Micro-royalty pool streaming'],
    sender_admin: 'Cody Germain (Lead Architect)',
  },
];

export const INITIAL_ROYALTY_EVENTS: RoyaltyStreamEvent[] = [
  {
    id: 'evt_001',
    timestamp: 'Just now',
    trigger_prompt: 'Synthesize responsive cart checkout with state sync',
    app_source: 'ShareShop Pro',
    amount_cents: 4.8,
    recipient_name: 'Cody Germain',
    package_or_work: '@reforge/kernel',
    stripe_transfer_id: 'tr_test_99218A',
    audit_hash: '0x99e8a...331b',
  },
  {
    id: 'evt_002',
    timestamp: '1 min ago',
    trigger_prompt: 'Synthesize acoustic rhythm section for commercial reel',
    app_source: 'Lyria Studio',
    amount_cents: 3.2,
    recipient_name: 'Marcus Vance',
    package_or_work: 'Harmonic Stems Vol. 4',
    stripe_transfer_id: 'tr_test_88192K',
    audit_hash: '0x71fa0...c902',
  },
  {
    id: 'evt_003',
    timestamp: '4 mins ago',
    trigger_prompt: 'Synthesize clean lucide icon badge with glowing border',
    app_source: 'CodeSynthesizer',
    amount_cents: 2.5,
    recipient_name: 'Amina Al-Mansoor',
    package_or_work: 'Artisan UI Glyphs',
    stripe_transfer_id: 'tr_test_11209B',
    audit_hash: '0x43bc1...e881',
  },
];

export const INITIAL_SUMMARY: RoyaltyPoolSummary = {
  total_streamed_usd: 128450.00,
  total_active_creators: 1420,
  total_synthesis_events: 384910,
  copyleft_quarantine_violations: 0,
  active_badge_apps: 89,
  monthly_pool_growth_pct: 34.8,
};
